# -*- coding: utf-8 -*-
"""examen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Elrica666/ee92e8c782f921025191a0e35ac0c9cf/examen.ipynb
"""

import random
def primo(num):
    if num <= 2:
        return False
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

def mediana(a, b, c):
    lista = [a, b, c]
    lista.sort()
    return lista[1]

def sig_primo(entrada):
  primo(entrada)
  entrada= entrada+1
  while primo(entrada) == False:
    entrada = entrada+1
    if primo(entrada) == True:
      print(entrada)
      break

def generar_contraseña():
    caracteres = [chr(i) for i in range(33, 127)]
    longitud = random.randint(7, 10)
    contraseña = ''.join(random.choice(caracteres) for _ in range(longitud))

    return contraseña

def calcular_hipotenusa(lado1, lado2):
    hipotenusa = (lado1 ** 2 + lado2 ** 2) ** 0.5
    print("La hipotenusa del triángulo rectángulo es: ", hipotenusa)
    return
